import { LinkItem, UserProfile } from "@/types";

export const SITE_CONFIG = {
  name: "마이링크",
  description: "나만의 중요한 링크들을 한곳에서 깔끔하게 모아볼 수 있어요.",
  url: "https://mylink.me",
};

export const DEFAULT_PROFILE: UserProfile = {
  id: "user-1",
  name: "홍길동",
  handle: "@gildong.dev",
  role: "프론트엔드 & 프로덕트 엔지니어",
  bio: "문제를 기술로 풀고 사용자 중심의 가치를 만드는 개발자예요.\n새로운 기술을 빠르게 배우고, 아이디어를 완성도 높은 프로덕트로 구현하는 과정을 즐겨요.",
  location: "서울, 대한민국",
  email: "gildong.developer@gmail.com",
  statusText: "새로운 협업과 프로젝트를 찾고 있어요 ✨",
  isAvailableForWork: true,
  tags: [
    "프론트엔드",
    "React",
    "Next.js",
    "TypeScript",
    "TailwindCSS",
    "프로덕트 디자인",
  ],
  socials: [
    { platform: "github", url: "https://github.com", label: "GitHub" },
    { platform: "linkedin", url: "https://linkedin.com", label: "LinkedIn" },
    { platform: "blog", url: "https://velog.io", label: "블로그" },
    { platform: "twitter", url: "https://x.com", label: "X" },
    { platform: "email", url: "mailto:gildong.developer@gmail.com", label: "이메일" },
  ],
  stats: [
    { label: "프로젝트", value: "14개", iconName: "FolderGit2" },
    { label: "누적 조회수", value: "1.4k회", iconName: "MousePointerClick" },
    { label: "기술 스택", value: "8개+", iconName: "Layers" },
    { label: "평균 응답", value: "1시간 내", iconName: "Zap" },
  ],
  links: [],
};

export const DEFAULT_CATEGORIES = [
  { id: "all", name: "전체", slug: "all" },
  { id: "project", name: "프로젝트", slug: "project" },
  { id: "work", name: "업무 & 커리어", slug: "work" },
  { id: "social", name: "블로그 & SNS", slug: "social" },
  { id: "tool", name: "도구 & 자료", slug: "tool" },
];

export const INITIAL_LINKS: LinkItem[] = [
  {
    id: "1",
    title: "2026 인터랙티브 포트폴리오",
    url: "https://github.com",
    description: "Next.js와 Tailwind로 구현한 반응형 포트폴리오 웹사이트예요",
    category: "project",
    icon: "sparkles",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    clickCount: 142,
    badge: "대표작",
    featured: true,
  },
  {
    id: "2",
    title: "GitHub 메인 프로필",
    url: "https://github.com",
    description: "진행 중인 오픈소스 기여와 개인 프로젝트 저장소예요",
    category: "work",
    icon: "github",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    clickCount: 98,
    badge: "인기",
  },
  {
    id: "3",
    title: "노션 이력서 & 경력기술서",
    url: "https://notion.so",
    description: "학력, 주요 경력, 프로젝트 성과를 자세히 정리해두었어요",
    category: "work",
    icon: "fileText",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    clickCount: 84,
    badge: "추천",
  },
  {
    id: "4",
    title: "개발 기술 블로그",
    url: "https://velog.io",
    description: "Next.js 트렌드와 프론트엔드 최적화 이야기를 연재하고 있어요",
    category: "social",
    icon: "bookOpen",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    clickCount: 65,
  },
  {
    id: "5",
    title: "Next.js 16 공식 개발 문서",
    url: "https://nextjs.org/docs",
    description: "App Router와 Turbopack 최신 레퍼런스를 확인할 수 있어요",
    category: "tool",
    icon: "globe",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    clickCount: 42,
  },
  {
    id: "6",
    title: "커피챗 1:1 일정 예약",
    url: "https://cal.com",
    description: "가벼운 네트워킹이나 협업 제안 미팅을 예약할 수 있어요",
    category: "project",
    icon: "coffee",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    clickCount: 31,
    badge: "NEW",
  },
];
