import { LinkItem, UserProfile } from "@/types";

export const SITE_CONFIG = {
  name: "마이링크 (MyLink)",
  description: "나만의 중요한 링크들을 한곳에서 깔끔하게 관리하고 공유하세요.",
  url: "https://mylink.me",
};

export const DEFAULT_PROFILE: UserProfile = {
  id: "user-1",
  name: "홍길동",
  handle: "@gildong.dev",
  role: "Frontend & Product Engineer",
  bio: "문제를 기술로 풀고 사용자 중심의 가치를 만드는 개발자입니다.\n새로운 기술을 빠르게 습득하며, 아이디어를 완성도 높은 프로덕트로 구현하는 과정을 즐깁니다.",
  location: "Seoul, South Korea",
  email: "gildong.developer@gmail.com",
  statusText: "새로운 협업 및 프로젝트 기회 탐색 중 ✨",
  isAvailableForWork: true,
  tags: [
    "#Frontend",
    "#React",
    "#Next.js",
    "#TypeScript",
    "#TailwindCSS",
    "#ProductDesign",
  ],
  socials: [
    { platform: "github", url: "https://github.com", label: "GitHub" },
    { platform: "linkedin", url: "https://linkedin.com", label: "LinkedIn" },
    { platform: "blog", url: "https://velog.io", label: "Tech Blog" },
    { platform: "twitter", url: "https://x.com", label: "X / Twitter" },
    { platform: "email", url: "mailto:gildong.developer@gmail.com", label: "Email" },
  ],
  stats: [
    { label: "프로젝트", value: "14+", iconName: "FolderGit2" },
    { label: "누적 클릭수", value: "1.4k+", iconName: "MousePointerClick" },
    { label: "기술 스택", value: "8+", iconName: "Layers" },
    { label: "평균 응답", value: "1시간 내", iconName: "Zap" },
  ],
  links: [],
};

export const DEFAULT_CATEGORIES = [
  { id: "all", name: "전체", slug: "all" },
  { id: "project", name: "프로젝트", slug: "project" },
  { id: "work", name: "업무 & 커리어", slug: "work" },
  { id: "social", name: "블로그 & SNS", slug: "social" },
  { id: "tool", name: "도구 & 자료", slug: "tool" },
];

export const INITIAL_LINKS: LinkItem[] = [
  {
    id: "1",
    title: "2026 인터랙티브 포트폴리오",
    url: "https://github.com",
    description: "Next.js, Three.js, Tailwind로 구현한 인터랙티브 반응형 개인 웹사이트",
    category: "project",
    icon: "sparkles",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    clickCount: 142,
    badge: "⭐️ 대표작",
    featured: true,
  },
  {
    id: "2",
    title: "GitHub 메인 프로필 & 오픈소스",
    url: "https://github.com",
    description: "진행 중인 오픈소스 기여 및 개인 사이드 프로젝트 저장소",
    category: "work",
    icon: "github",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    clickCount: 98,
    badge: "🔥 인기",
  },
  {
    id: "3",
    title: "Notion 인터랙티브 이력서",
    url: "https://notion.so",
    description: "학력, 주요 경력, 프로젝트 세부 성과 및 기술 역량 상세 정리",
    category: "work",
    icon: "fileText",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    clickCount: 84,
    badge: "추천",
  },
  {
    id: "4",
    title: "Velog 개발 기술 블로그",
    url: "https://velog.io",
    description: "Next.js 16 트렌드, 웹 성능 최적화, 프론트엔드 아키텍처 연재",
    category: "social",
    icon: "bookOpen",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    clickCount: 65,
  },
  {
    id: "5",
    title: "Next.js 16 공식 개발 가이드",
    url: "https://nextjs.org/docs",
    description: "Turbopack 및 App Router 최신 아키텍처 학습용 레퍼런스",
    category: "tool",
    icon: "globe",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    clickCount: 42,
  },
  {
    id: "6",
    title: "커피챗 & 협업 문의 (1:1 미팅)",
    url: "https://cal.com",
    description: "프로젝트 제안, 사이드 프로젝트 아이디어 협의, 커피챗 일정 예약",
    category: "project",
    icon: "coffee",
    isPublic: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    clickCount: 31,
    badge: "NEW",
  },
];
